name: SNYK-IaC-SCAN

on:
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ncatslnghrunpdv02.ncats.nih.gov
    steps:
      - uses: actions/checkout@v3

      # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
      - name: Snyk IaC report
        run: snyk iac test --report --sarif-file-output=snyk-code.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_CLI }}
          FORCE_COLOR: true

      # Push the Snyk report results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
      
      # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to JSON.
      - name: Generate JSON of Snyk report
        run: snyk iac test --json-file-output=snyk_iac_results.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_CLI }}
          FORCE_COLOR: true
      
      # Push the Snyk JSON report to Github artifacts 
      - name: Upload Snyk IaC JSON report
        uses: actions/upload-artifact@v4
        with:
          name: snyk_iac_results
          path: snyk_iac_results.json
      
      # Runs Snyk Infrastructure as Code (IaC) Test for Critical and Highs
      - name: Snyk IaC test 
        run: |
          snyk iac test --severity-threshold=critical
          snyk iac test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_CLI }}
          FORCE_COLOR: true
