pipeline {
    options {
        timestamps()
        skipDefaultCheckout()
    }
    agent {label 'internal-build.ncats'}
    parameters {
        choice(name: 'Action', choices: 'plan\napply', description: 'Manual build stages')
        string(name: 'ENVIRONMENT', defaultValue: 'cpe', description: 'Role Name (mandatory)')
    }
    triggers {
        pollSCM('H/10 * * * *')
    }
    environment {
        PROJECT_NAME     = "aws-ifx-infra"
        INIT_TOKEN       = credentials('Vault-Access')                        // OIDC provider this token is Auto Generated //
        SPHINX_TOKEN     = credentials('ncatssvcdvops-platform-services')     // PatToken Read Only Access for the DevOps Artifacts Repo https://github.com/Sphinx-Automation/devops-pipeline-artifacts.git //
        ROLE_NAME        = "$ENVIRONMENT-$PROJECT_NAME"                      // Role Name is Mandatory Variable for Vault //
        APP_TYPE         = "deploy-api-keys"
        SUB_PATH         = "aws-ifx"
    }
    stages {
        stage('getSecrets By Role') {
            steps {
                cleanWs()
                checkout scm
                script {
                sh '''
                    ### Cloning the repo from DevOps Artifacts Repository Repo ###
                    git clone https://$SPHINX_TOKEN@github.com/Sphinx-Automation/devops-pipeline-artifacts.git
                    ###  Running the script with Env specific to Authenticate Vault & Get Application Secrets for Docker Token###
                    cd devops-pipeline-artifacts/application
                    /bin/bash getAppSecretsByRole.sh
                    '''
                }
            }
        }
        stage('Submodule and Terraform Init') {
            when {
                anyOf {
                    changeset "aws/aws-ifx/**"
                    triggeredBy 'UserIdCause'
                }
            }
            steps {
                configFileProvider([
                    configFile(fileId: 'prepare.sh', targetLocation: 'prepare.sh')
                ]){
                sh '''#!/bin/bash
                    source prepare.sh
                    echo -e "[submodule "terraform-modules"]\n        path = terraform-modules\n        url = https://$SPHINX_TOKEN@github.com/Sphinx-Automation/terraform-modules.git\n" > .gitmodules
                    sed -i 's/terraform-modules/"terraform-modules"/' .gitmodules
                    git submodule update --init --recursive; sleep 10s
                    git submodule update --remote --merge; sleep 10s
                    '''
                ansiColor('xterm') {
                    sh 'cd aws/aws-ifx; terraform1.2.4 init'
                    }
                }
            }
        }
        stage('Terraform Plan') {
            when {
                anyOf {
                    changeset "aws/aws-ifx/**"
                    triggeredBy 'UserIdCause'
                }
            }
            steps {
                ansiColor('xterm') {
                    sh 'cd aws/aws-ifx; terraform1.2.4 plan'
                }
            }
        }
        stage('Terraform Apply') {
            when {
                allOf {
                    expression {
                        params.Action == 'apply'
                    }
                    anyOf {
                        changeset "aws/aws-ifx/**"
                        triggeredBy 'UserIdCause'
                    }
                }
            }
            steps {
                ansiColor('xterm') {
                    sh 'cd aws/aws-ifx; terraform1.2.4 apply -auto-approve'
                }
            }
        }
    }
    post {
        always {
            echo " Clean up the workspace in deploy node!"
            cleanWs()
        }
    }
}
